// Generated by gencpp from file logger_service/GetLoggingStatus.msg
// DO NOT EDIT!


#ifndef LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUS_H
#define LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUS_H

#include <ros/service_traits.h>


#include <logger_service/GetLoggingStatusRequest.h>
#include <logger_service/GetLoggingStatusResponse.h>


namespace logger_service
{

struct GetLoggingStatus
{

typedef GetLoggingStatusRequest Request;
typedef GetLoggingStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLoggingStatus
} // namespace logger_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::logger_service::GetLoggingStatus > {
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::logger_service::GetLoggingStatus&) { return value(); }
};

template<>
struct DataType< ::logger_service::GetLoggingStatus > {
  static const char* value()
  {
    return "logger_service/GetLoggingStatus";
  }

  static const char* value(const ::logger_service::GetLoggingStatus&) { return value(); }
};


// service_traits::MD5Sum< ::logger_service::GetLoggingStatusRequest> should match
// service_traits::MD5Sum< ::logger_service::GetLoggingStatus >
template<>
struct MD5Sum< ::logger_service::GetLoggingStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::logger_service::GetLoggingStatus >::value();
  }
  static const char* value(const ::logger_service::GetLoggingStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::logger_service::GetLoggingStatusRequest> should match
// service_traits::DataType< ::logger_service::GetLoggingStatus >
template<>
struct DataType< ::logger_service::GetLoggingStatusRequest>
{
  static const char* value()
  {
    return DataType< ::logger_service::GetLoggingStatus >::value();
  }
  static const char* value(const ::logger_service::GetLoggingStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::logger_service::GetLoggingStatusResponse> should match
// service_traits::MD5Sum< ::logger_service::GetLoggingStatus >
template<>
struct MD5Sum< ::logger_service::GetLoggingStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::logger_service::GetLoggingStatus >::value();
  }
  static const char* value(const ::logger_service::GetLoggingStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::logger_service::GetLoggingStatusResponse> should match
// service_traits::DataType< ::logger_service::GetLoggingStatus >
template<>
struct DataType< ::logger_service::GetLoggingStatusResponse>
{
  static const char* value()
  {
    return DataType< ::logger_service::GetLoggingStatus >::value();
  }
  static const char* value(const ::logger_service::GetLoggingStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUS_H
