// Generated by gencpp from file logger_service/GetLoggingStatusResponse.msg
// DO NOT EDIT!


#ifndef LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSRESPONSE_H
#define LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace logger_service
{
template <class ContainerAllocator>
struct GetLoggingStatusResponse_
{
  typedef GetLoggingStatusResponse_<ContainerAllocator> Type;

  GetLoggingStatusResponse_()
    : status(false)  {
    }
  GetLoggingStatusResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetLoggingStatusResponse_

typedef ::logger_service::GetLoggingStatusResponse_<std::allocator<void> > GetLoggingStatusResponse;

typedef boost::shared_ptr< ::logger_service::GetLoggingStatusResponse > GetLoggingStatusResponsePtr;
typedef boost::shared_ptr< ::logger_service::GetLoggingStatusResponse const> GetLoggingStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator1> & lhs, const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator1> & lhs, const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace logger_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "logger_service/GetLoggingStatusResponse";
  }

  static const char* value(const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLoggingStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::logger_service::GetLoggingStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::logger_service::GetLoggingStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSRESPONSE_H
