// Generated by gencpp from file logger_service/GetLoggingStatusRequest.msg
// DO NOT EDIT!


#ifndef LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSREQUEST_H
#define LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace logger_service
{
template <class ContainerAllocator>
struct GetLoggingStatusRequest_
{
  typedef GetLoggingStatusRequest_<ContainerAllocator> Type;

  GetLoggingStatusRequest_()
    {
    }
  GetLoggingStatusRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLoggingStatusRequest_

typedef ::logger_service::GetLoggingStatusRequest_<std::allocator<void> > GetLoggingStatusRequest;

typedef boost::shared_ptr< ::logger_service::GetLoggingStatusRequest > GetLoggingStatusRequestPtr;
typedef boost::shared_ptr< ::logger_service::GetLoggingStatusRequest const> GetLoggingStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace logger_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::logger_service::GetLoggingStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "logger_service/GetLoggingStatusRequest";
  }

  static const char* value(const ::logger_service::GetLoggingStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::logger_service::GetLoggingStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLoggingStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::logger_service::GetLoggingStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::logger_service::GetLoggingStatusRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LOGGER_SERVICE_MESSAGE_GETLOGGINGSTATUSREQUEST_H
