// Generated by gencpp from file logger_service/ToggleLogging.msg
// DO NOT EDIT!


#ifndef LOGGER_SERVICE_MESSAGE_TOGGLELOGGING_H
#define LOGGER_SERVICE_MESSAGE_TOGGLELOGGING_H

#include <ros/service_traits.h>


#include <logger_service/ToggleLoggingRequest.h>
#include <logger_service/ToggleLoggingResponse.h>


namespace logger_service
{

struct ToggleLogging
{

typedef ToggleLoggingRequest Request;
typedef ToggleLoggingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleLogging
} // namespace logger_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::logger_service::ToggleLogging > {
  static const char* value()
  {
    return "fecf66bb22f64ee8735af9d41647765f";
  }

  static const char* value(const ::logger_service::ToggleLogging&) { return value(); }
};

template<>
struct DataType< ::logger_service::ToggleLogging > {
  static const char* value()
  {
    return "logger_service/ToggleLogging";
  }

  static const char* value(const ::logger_service::ToggleLogging&) { return value(); }
};


// service_traits::MD5Sum< ::logger_service::ToggleLoggingRequest> should match
// service_traits::MD5Sum< ::logger_service::ToggleLogging >
template<>
struct MD5Sum< ::logger_service::ToggleLoggingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::logger_service::ToggleLogging >::value();
  }
  static const char* value(const ::logger_service::ToggleLoggingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::logger_service::ToggleLoggingRequest> should match
// service_traits::DataType< ::logger_service::ToggleLogging >
template<>
struct DataType< ::logger_service::ToggleLoggingRequest>
{
  static const char* value()
  {
    return DataType< ::logger_service::ToggleLogging >::value();
  }
  static const char* value(const ::logger_service::ToggleLoggingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::logger_service::ToggleLoggingResponse> should match
// service_traits::MD5Sum< ::logger_service::ToggleLogging >
template<>
struct MD5Sum< ::logger_service::ToggleLoggingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::logger_service::ToggleLogging >::value();
  }
  static const char* value(const ::logger_service::ToggleLoggingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::logger_service::ToggleLoggingResponse> should match
// service_traits::DataType< ::logger_service::ToggleLogging >
template<>
struct DataType< ::logger_service::ToggleLoggingResponse>
{
  static const char* value()
  {
    return DataType< ::logger_service::ToggleLogging >::value();
  }
  static const char* value(const ::logger_service::ToggleLoggingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOGGER_SERVICE_MESSAGE_TOGGLELOGGING_H
