// Generated by gencpp from file logger_service/ToggleLoggingRequest.msg
// DO NOT EDIT!


#ifndef LOGGER_SERVICE_MESSAGE_TOGGLELOGGINGREQUEST_H
#define LOGGER_SERVICE_MESSAGE_TOGGLELOGGINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace logger_service
{
template <class ContainerAllocator>
struct ToggleLoggingRequest_
{
  typedef ToggleLoggingRequest_<ContainerAllocator> Type;

  ToggleLoggingRequest_()
    : loggingEnabled(false)  {
    }
  ToggleLoggingRequest_(const ContainerAllocator& _alloc)
    : loggingEnabled(false)  {
  (void)_alloc;
    }



   typedef uint8_t _loggingEnabled_type;
  _loggingEnabled_type loggingEnabled;





  typedef boost::shared_ptr< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleLoggingRequest_

typedef ::logger_service::ToggleLoggingRequest_<std::allocator<void> > ToggleLoggingRequest;

typedef boost::shared_ptr< ::logger_service::ToggleLoggingRequest > ToggleLoggingRequestPtr;
typedef boost::shared_ptr< ::logger_service::ToggleLoggingRequest const> ToggleLoggingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::logger_service::ToggleLoggingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::logger_service::ToggleLoggingRequest_<ContainerAllocator1> & lhs, const ::logger_service::ToggleLoggingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.loggingEnabled == rhs.loggingEnabled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::logger_service::ToggleLoggingRequest_<ContainerAllocator1> & lhs, const ::logger_service::ToggleLoggingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace logger_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0bf3b89fe2a5cd89cc4d28dc3bf08ee";
  }

  static const char* value(const ::logger_service::ToggleLoggingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0bf3b89fe2a5cd8ULL;
  static const uint64_t static_value2 = 0x9cc4d28dc3bf08eeULL;
};

template<class ContainerAllocator>
struct DataType< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "logger_service/ToggleLoggingRequest";
  }

  static const char* value(const ::logger_service::ToggleLoggingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool loggingEnabled\n"
;
  }

  static const char* value(const ::logger_service::ToggleLoggingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.loggingEnabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleLoggingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::logger_service::ToggleLoggingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::logger_service::ToggleLoggingRequest_<ContainerAllocator>& v)
  {
    s << indent << "loggingEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loggingEnabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOGGER_SERVICE_MESSAGE_TOGGLELOGGINGREQUEST_H
