(cl:defpackage setting_msg-srv
  (:use )
  (:export
   "CONFIGURATIONSERVICE"
   "<CONFIGURATIONSERVICE-REQUEST>"
   "CONFIGURATIONSERVICE-REQUEST"
   "<CONFIGURATIONSERVICE-RESPONSE>"
   "CONFIGURATIONSERVICE-RESPONSE"
   "IMUOFFSETSERVICE"
   "<IMUOFFSETSERVICE-REQUEST>"
   "IMUOFFSETSERVICE-REQUEST"
   "<IMUOFFSETSERVICE-RESPONSE>"
   "IMUOFFSETSERVICE-RESPONSE"
  ))

