// Generated by gencpp from file state_controller_msg/GetStateService.msg
// DO NOT EDIT!


#ifndef STATE_CONTROLLER_MSG_MESSAGE_GETSTATESERVICE_H
#define STATE_CONTROLLER_MSG_MESSAGE_GETSTATESERVICE_H

#include <ros/service_traits.h>


#include <state_controller_msg/GetStateServiceRequest.h>
#include <state_controller_msg/GetStateServiceResponse.h>


namespace state_controller_msg
{

struct GetStateService
{

typedef GetStateServiceRequest Request;
typedef GetStateServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStateService
} // namespace state_controller_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_controller_msg::GetStateService > {
  static const char* value()
  {
    return "602e363368600eff1e586ce78104a17a";
  }

  static const char* value(const ::state_controller_msg::GetStateService&) { return value(); }
};

template<>
struct DataType< ::state_controller_msg::GetStateService > {
  static const char* value()
  {
    return "state_controller_msg/GetStateService";
  }

  static const char* value(const ::state_controller_msg::GetStateService&) { return value(); }
};


// service_traits::MD5Sum< ::state_controller_msg::GetStateServiceRequest> should match
// service_traits::MD5Sum< ::state_controller_msg::GetStateService >
template<>
struct MD5Sum< ::state_controller_msg::GetStateServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_controller_msg::GetStateService >::value();
  }
  static const char* value(const ::state_controller_msg::GetStateServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_controller_msg::GetStateServiceRequest> should match
// service_traits::DataType< ::state_controller_msg::GetStateService >
template<>
struct DataType< ::state_controller_msg::GetStateServiceRequest>
{
  static const char* value()
  {
    return DataType< ::state_controller_msg::GetStateService >::value();
  }
  static const char* value(const ::state_controller_msg::GetStateServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_controller_msg::GetStateServiceResponse> should match
// service_traits::MD5Sum< ::state_controller_msg::GetStateService >
template<>
struct MD5Sum< ::state_controller_msg::GetStateServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_controller_msg::GetStateService >::value();
  }
  static const char* value(const ::state_controller_msg::GetStateServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_controller_msg::GetStateServiceResponse> should match
// service_traits::DataType< ::state_controller_msg::GetStateService >
template<>
struct DataType< ::state_controller_msg::GetStateServiceResponse>
{
  static const char* value()
  {
    return DataType< ::state_controller_msg::GetStateService >::value();
  }
  static const char* value(const ::state_controller_msg::GetStateServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_CONTROLLER_MSG_MESSAGE_GETSTATESERVICE_H
