// Generated by gencpp from file setting_msg/ConfigurationServiceRequest.msg
// DO NOT EDIT!


#ifndef SETTING_MSG_MESSAGE_CONFIGURATIONSERVICEREQUEST_H
#define SETTING_MSG_MESSAGE_CONFIGURATIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace setting_msg
{
template <class ContainerAllocator>
struct ConfigurationServiceRequest_
{
  typedef ConfigurationServiceRequest_<ContainerAllocator> Type;

  ConfigurationServiceRequest_()
    : key()  {
    }
  ConfigurationServiceRequest_(const ContainerAllocator& _alloc)
    : key(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigurationServiceRequest_

typedef ::setting_msg::ConfigurationServiceRequest_<std::allocator<void> > ConfigurationServiceRequest;

typedef boost::shared_ptr< ::setting_msg::ConfigurationServiceRequest > ConfigurationServiceRequestPtr;
typedef boost::shared_ptr< ::setting_msg::ConfigurationServiceRequest const> ConfigurationServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator1> & lhs, const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator1> & lhs, const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace setting_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0e6b82860d1fefbdaa2c52c0b6f712e";
  }

  static const char* value(const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0e6b82860d1fefbULL;
  static const uint64_t static_value2 = 0xdaa2c52c0b6f712eULL;
};

template<class ContainerAllocator>
struct DataType< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "setting_msg/ConfigurationServiceRequest";
  }

  static const char* value(const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
;
  }

  static const char* value(const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigurationServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::setting_msg::ConfigurationServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SETTING_MSG_MESSAGE_CONFIGURATIONSERVICEREQUEST_H
