// Generated by gencpp from file setting_msg/ImuOffsetServiceResponse.msg
// DO NOT EDIT!


#ifndef SETTING_MSG_MESSAGE_IMUOFFSETSERVICERESPONSE_H
#define SETTING_MSG_MESSAGE_IMUOFFSETSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace setting_msg
{
template <class ContainerAllocator>
struct ImuOffsetServiceResponse_
{
  typedef ImuOffsetServiceResponse_<ContainerAllocator> Type;

  ImuOffsetServiceResponse_()
    : value()  {
    }
  ImuOffsetServiceResponse_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImuOffsetServiceResponse_

typedef ::setting_msg::ImuOffsetServiceResponse_<std::allocator<void> > ImuOffsetServiceResponse;

typedef boost::shared_ptr< ::setting_msg::ImuOffsetServiceResponse > ImuOffsetServiceResponsePtr;
typedef boost::shared_ptr< ::setting_msg::ImuOffsetServiceResponse const> ImuOffsetServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator1> & lhs, const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator1> & lhs, const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace setting_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64e58419496c7248b4ef25731f88b8c3";
  }

  static const char* value(const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64e58419496c7248ULL;
  static const uint64_t static_value2 = 0xb4ef25731f88b8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "setting_msg/ImuOffsetServiceResponse";
  }

  static const char* value(const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string value\n"
"\n"
;
  }

  static const char* value(const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuOffsetServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::setting_msg::ImuOffsetServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SETTING_MSG_MESSAGE_IMUOFFSETSERVICERESPONSE_H
