// Generated by gencpp from file setting_msg/ImuOffsetService.msg
// DO NOT EDIT!


#ifndef SETTING_MSG_MESSAGE_IMUOFFSETSERVICE_H
#define SETTING_MSG_MESSAGE_IMUOFFSETSERVICE_H

#include <ros/service_traits.h>


#include <setting_msg/ImuOffsetServiceRequest.h>
#include <setting_msg/ImuOffsetServiceResponse.h>


namespace setting_msg
{

struct ImuOffsetService
{

typedef ImuOffsetServiceRequest Request;
typedef ImuOffsetServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuOffsetService
} // namespace setting_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::setting_msg::ImuOffsetService > {
  static const char* value()
  {
    return "f17e28b74ba2da00db559b27e3cb5a7f";
  }

  static const char* value(const ::setting_msg::ImuOffsetService&) { return value(); }
};

template<>
struct DataType< ::setting_msg::ImuOffsetService > {
  static const char* value()
  {
    return "setting_msg/ImuOffsetService";
  }

  static const char* value(const ::setting_msg::ImuOffsetService&) { return value(); }
};


// service_traits::MD5Sum< ::setting_msg::ImuOffsetServiceRequest> should match
// service_traits::MD5Sum< ::setting_msg::ImuOffsetService >
template<>
struct MD5Sum< ::setting_msg::ImuOffsetServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::setting_msg::ImuOffsetService >::value();
  }
  static const char* value(const ::setting_msg::ImuOffsetServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::setting_msg::ImuOffsetServiceRequest> should match
// service_traits::DataType< ::setting_msg::ImuOffsetService >
template<>
struct DataType< ::setting_msg::ImuOffsetServiceRequest>
{
  static const char* value()
  {
    return DataType< ::setting_msg::ImuOffsetService >::value();
  }
  static const char* value(const ::setting_msg::ImuOffsetServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::setting_msg::ImuOffsetServiceResponse> should match
// service_traits::MD5Sum< ::setting_msg::ImuOffsetService >
template<>
struct MD5Sum< ::setting_msg::ImuOffsetServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::setting_msg::ImuOffsetService >::value();
  }
  static const char* value(const ::setting_msg::ImuOffsetServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::setting_msg::ImuOffsetServiceResponse> should match
// service_traits::DataType< ::setting_msg::ImuOffsetService >
template<>
struct DataType< ::setting_msg::ImuOffsetServiceResponse>
{
  static const char* value()
  {
    return DataType< ::setting_msg::ImuOffsetService >::value();
  }
  static const char* value(const ::setting_msg::ImuOffsetServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SETTING_MSG_MESSAGE_IMUOFFSETSERVICE_H
