// Generated by gencpp from file setting_msg/Setting.msg
// DO NOT EDIT!


#ifndef SETTING_MSG_MESSAGE_SETTING_H
#define SETTING_MSG_MESSAGE_SETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace setting_msg
{
template <class ContainerAllocator>
struct Setting_
{
  typedef Setting_<ContainerAllocator> Type;

  Setting_()
    : key()
    , value()  {
    }
  Setting_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::setting_msg::Setting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::setting_msg::Setting_<ContainerAllocator> const> ConstPtr;

}; // struct Setting_

typedef ::setting_msg::Setting_<std::allocator<void> > Setting;

typedef boost::shared_ptr< ::setting_msg::Setting > SettingPtr;
typedef boost::shared_ptr< ::setting_msg::Setting const> SettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::setting_msg::Setting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::setting_msg::Setting_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::setting_msg::Setting_<ContainerAllocator1> & lhs, const ::setting_msg::Setting_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::setting_msg::Setting_<ContainerAllocator1> & lhs, const ::setting_msg::Setting_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace setting_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::Setting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::setting_msg::Setting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::Setting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::setting_msg::Setting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::Setting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::setting_msg::Setting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::setting_msg::Setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf57fdc6617a881a88c16e768132149c";
  }

  static const char* value(const ::setting_msg::Setting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf57fdc6617a881aULL;
  static const uint64_t static_value2 = 0x88c16e768132149cULL;
};

template<class ContainerAllocator>
struct DataType< ::setting_msg::Setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "setting_msg/Setting";
  }

  static const char* value(const ::setting_msg::Setting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::setting_msg::Setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
"string value\n"
"\n"
;
  }

  static const char* value(const ::setting_msg::Setting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::setting_msg::Setting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Setting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::setting_msg::Setting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::setting_msg::Setting_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SETTING_MSG_MESSAGE_SETTING_H
