// Generated by gencpp from file inertial_sense/FirmwareUpdateRequest.msg
// DO NOT EDIT!


#ifndef INERTIAL_SENSE_MESSAGE_FIRMWAREUPDATEREQUEST_H
#define INERTIAL_SENSE_MESSAGE_FIRMWAREUPDATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inertial_sense
{
template <class ContainerAllocator>
struct FirmwareUpdateRequest_
{
  typedef FirmwareUpdateRequest_<ContainerAllocator> Type;

  FirmwareUpdateRequest_()
    : filename()  {
    }
  FirmwareUpdateRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FirmwareUpdateRequest_

typedef ::inertial_sense::FirmwareUpdateRequest_<std::allocator<void> > FirmwareUpdateRequest;

typedef boost::shared_ptr< ::inertial_sense::FirmwareUpdateRequest > FirmwareUpdateRequestPtr;
typedef boost::shared_ptr< ::inertial_sense::FirmwareUpdateRequest const> FirmwareUpdateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator1> & lhs, const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator1> & lhs, const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inertial_sense

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inertial_sense/FirmwareUpdateRequest";
  }

  static const char* value(const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n"
;
  }

  static const char* value(const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FirmwareUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inertial_sense::FirmwareUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INERTIAL_SENSE_MESSAGE_FIRMWAREUPDATEREQUEST_H
