// Generated by gencpp from file inertial_sense/GTime.msg
// DO NOT EDIT!


#ifndef INERTIAL_SENSE_MESSAGE_GTIME_H
#define INERTIAL_SENSE_MESSAGE_GTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inertial_sense
{
template <class ContainerAllocator>
struct GTime_
{
  typedef GTime_<ContainerAllocator> Type;

  GTime_()
    : time(0)
    , sec(0.0)  {
    }
  GTime_(const ContainerAllocator& _alloc)
    : time(0)
    , sec(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _time_type;
  _time_type time;

   typedef double _sec_type;
  _sec_type sec;





  typedef boost::shared_ptr< ::inertial_sense::GTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inertial_sense::GTime_<ContainerAllocator> const> ConstPtr;

}; // struct GTime_

typedef ::inertial_sense::GTime_<std::allocator<void> > GTime;

typedef boost::shared_ptr< ::inertial_sense::GTime > GTimePtr;
typedef boost::shared_ptr< ::inertial_sense::GTime const> GTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inertial_sense::GTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inertial_sense::GTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inertial_sense::GTime_<ContainerAllocator1> & lhs, const ::inertial_sense::GTime_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.sec == rhs.sec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inertial_sense::GTime_<ContainerAllocator1> & lhs, const ::inertial_sense::GTime_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inertial_sense

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inertial_sense::GTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inertial_sense::GTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inertial_sense::GTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inertial_sense::GTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inertial_sense::GTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inertial_sense::GTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inertial_sense::GTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f27debe4939acc53511906e7b35f8f58";
  }

  static const char* value(const ::inertial_sense::GTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf27debe4939acc53ULL;
  static const uint64_t static_value2 = 0x511906e7b35f8f58ULL;
};

template<class ContainerAllocator>
struct DataType< ::inertial_sense::GTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inertial_sense/GTime";
  }

  static const char* value(const ::inertial_sense::GTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inertial_sense::GTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 time\n"
"float64 sec\n"
;
  }

  static const char* value(const ::inertial_sense::GTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inertial_sense::GTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.sec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inertial_sense::GTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inertial_sense::GTime_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
    s << indent << "sec: ";
    Printer<double>::stream(s, indent + "  ", v.sec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INERTIAL_SENSE_MESSAGE_GTIME_H
