(cl:defpackage logger_service-srv
  (:use )
  (:export
   "GETLOGGINGSTATUS"
   "<GETLOGGINGSTATUS-REQUEST>"
   "GETLOGGINGSTATUS-REQUEST"
   "<GETLOGGINGSTATUS-RESPONSE>"
   "GETLOGGINGSTATUS-RESPONSE"
   "TOGGLELOGGING"
   "<TOGGLELOGGING-REQUEST>"
   "TOGGLELOGGING-REQUEST"
   "<TOGGLELOGGING-RESPONSE>"
   "TOGGLELOGGING-RESPONSE"
  ))

